# Generated by Django 5.1.2 on 2024-10-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='titre')),
                ('label', models.CharField(max_length=100, verbose_name='description')),
                ('author', models.CharField(max_length=150, verbose_name='auteur')),
                ('published_year', models.IntegerField(verbose_name='année de publication')),
                ('cover', models.ImageField(upload_to='', verbose_name='couverture')),
            ],
        ),
    ]
