# Generated by Django 5.1.2 on 2024-11-05 01:26

import books.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nom')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='titre')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
                ('author', models.CharField(max_length=150, verbose_name='auteur')),
                ('published_date', models.DateTimeField(verbose_name='année de publication')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='cover/', verbose_name='couverture')),
                ('document', models.FileField(upload_to='document/', validators=[books.validators.validate_file_extension], verbose_name='document')),
                ('is_available', models.BooleanField(default=True, verbose_name='disponibilité')),
                ('stars', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('genre', models.ManyToManyField(related_name='books', to='books.genre')),
            ],
        ),
    ]
