# Generated by Django 5.1.2 on 2024-10-23 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_cover_image_alter_book_genre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='label',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='publication_date',
            new_name='published_date',
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='couverture'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AlterField(
            model_name='book',
            name='stars',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(related_name='books', to='books.genre'),
        ),
    ]
