# Generated by Django 5.1.2 on 2024-10-23 21:50

import books.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_label_book_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='available',
            new_name='is_available',
        ),
        migrations.AddField(
            model_name='book',
            name='document',
            field=models.FileField(null=True, upload_to='document/', validators=[books.validators.validate_file_extension], verbose_name='document'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='cover/', verbose_name='couverture'),
        ),
    ]
