# Generated by Django 5.1.2 on 2024-10-23 21:59

import books.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rename_available_book_is_available_book_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='document',
            field=models.FileField(upload_to='document/', validators=[books.validators.validate_file_extension], verbose_name='document'),
        ),
    ]
